### ISSUE TITLE
0.05 is too fast

### ISSUE THREAD

**Issue by SchumacherFarad** [AtaTrkgl/itu-ders-secici#1]
![resim_2024-02-12_104521662](https://github.com/AtaTrkgl/itu-ders-secici/assets/157172419/73395ee3-9387-4ee6-a681-531da5673110)

It's the first that I am receiving that error message.

**Comment by SchumacherFarad** [comment]
It might be something else(maybe one push with one token) because I changed the timer to 0.75 form 0.05 and nothing changed, it gets the same error.

**Comment by SchumacherFarad** [comment]
Yeah found the reason, it's just one push per one token.
![image](https://github.com/AtaTrkgl/itu-ders-secici/assets/157172419/232aea8c-a6af-4b75-bb85-fe853d00a281)

`    token = ""
        

    # Select courses, do it a few times just in case.
    Logger.log("Dersler Seçiliyor...")
    for _ in range(MAX_TRIES):
        new_token = token_fetcher.fetch_token()
        if "ERROR" not in new_token:
            token = new_token
        request_course_selection(token, crn_list)
        sleep(DELAY_BETWEEN_TRIES)
`

this solved the problem but it's 4 secs per push which is a large time maybe you can optimize it. I don't have necessary knowledge.

**Comment by SchumacherFarad** [comment]
It's not one push per token It's one push per second**

**Comment by AtaTrkgl** [comment]
@SchumacherFarad I hit the same API rate limit too. To fix it, I changed it so the code waits until the exact time and starts doing the requests with 1 second between each try in 540a3d2b7f66040e7eb79c27cd81cde16777ed44. The code seams to be working more consistently now.

I'd be glad if you could test it and close this issue if it's resolved ^^

**Comment by SchumacherFarad** [comment]
I had to reopen this issue due to an announcement posted today. kepler will limit us all to sending a request every 3 seconds so the DELAY_BETWEEN_TRIES at this line https://github.com/AtaTrkgl/itu-ders-secici/blob/48b18b663ef3db62c64602b4bf3ec21ce40d4b28/src/run.py#L18 should change again to 3

![image](https://github.com/user-attachments/assets/99f8dd87-a9f3-427d-b96c-1064d15a8680)

**Comment by AtaTrkgl** [comment]
It should be fixed with the latest commit
